### ISSUE TITLE
Can not support zabbix 3.2

### ISSUE THREAD

**Issue by canghai908** [cavaliercoder/g2z#9]
I use gopkg.in/cavaliercoder/g2z.v3/,but it is not support,the log is 

`` 19834:20170611:183512.625 Starting Zabbix Agent [Zabbix server]. Zabbix 3.2.6 (revision 67849).
 19834:20170611:183512.625 **** Enabled features ****
 19834:20170611:183512.625 IPv6 support:           NO
 19834:20170611:183512.625 TLS support:            NO
 19834:20170611:183512.625 **************************
 19834:20170611:183512.625 using configuration file: /usr/local/zabbix/etc/zabbix_agentd.conf
 19834:20170611:183512.628 unsupported module "dummy.so" version: 1
 19834:20170611:183512.628 loading modules failed, exiting...
~

**Comment by cavaliercoder** [comment]
Apologies, I haven't updated the codebase to support 3.2 yet. There were breaking changes in Zabbix again.

Please note that I have abandoned this project after issue #5, as goroutines become unstable after the Zabbix agent forks. If you still would like me address your issue, I can create a v3.2 fix.

**Comment by canghai908** [comment]
Thank you,Please create a v3.2 fix.I will use it  normally,my application is very simple.

**Comment by rockaut** [comment]
Heja @canghai908 This should have fixed with my PR. Forgot the "fixed" keyword sorry.

**Comment by canghai908** [comment]
@rockaut  Thank you!
